name: dishscan

channels:
  - conda-forge

dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib
    - scikit-learn
    - seaborn
    - tensorflow-datasets
    - tensorflow-addons
    - tensorflow[and-cuda]
